### ISSUE TITLE
process_all_timesteps aborts too early if only one timestep in task file

### ISSUE THREAD

**Issue by wolfidan** [MeteoSwiss/rainforest#2]
If one wants to process a task file with only one single timestep,  [retrieve_radar_data.py](https://github.com/MeteoSwiss/rainforest/blob/master/rainforest/database/retrieve_radar_data.py) and  [retrieve_reference_data.py](https://github.com/MeteoSwiss/rainforest/blob/master/rainforest/database/retrieve_reference_data.py) will not create an output file.

This is due to where the part

```
 if day_of_year != current_day or i == len(all_timesteps) - 1:
                logging.info('Saving new table for day {:s}'.format(str(current_day)))
                name = self.output_folder + current_day + '.parquet'
```
is located in the file. It happens too early. It should be placed at the very bottom of the main loop around line 526 in [retrieve_radar_data.py](https://github.com/MeteoSwiss/rainforest/blob/master/rainforest/database/retrieve_radar_data.py)  and line 344 in [retrieve_reference_data.py](https://github.com/MeteoSwiss/rainforest/blob/master/rainforest/database/retrieve_reference_data.py)

**Comment by gugerlir** [comment]
Moved the part of save file to the end of the loop solved the issue (see commit 392f72d023203d712cd74d15b285b840e10a459d)

**Comment by wolfidan** [comment]
Ciao @gugerlir , could you do it there as well. Or should I do it? Have a nice day

**Comment by gugerlir** [comment]
Ciao @wolfidan I changed the time reference here: #9020315927eb2c06bd575e8c10913a2aee271706. I am closing this issue now :)

**Comment by wolfidan** [comment]
Great, thanks @gugerlir
